# Machine Learning e Data Science com Python de A à Z – Completo

Instrutor: **Jones Granatyr**

https://www.udemy.com/machine-learning-e-data-science-com-python-y/

---

# Parte 1 - Classificação

---

## Introdução

* Pré-processamento e preparação de bases de dados para classificação
* Aprendizagem bayesiana (algoritmo Naive Bayes)
* Aprendizagem por árvores de decisão (algoritmo básico de árvores e Random Forest)
* Aprendizagem por regras (algoritmo OneR)
* Aprendizagem baseada em instâncias (algoritmo kNN)
* Regressão logística
* Máquinas de vetores de suporte (SVM)
* Redes neurais artificiais
* Avaliação de algoritmos de classificação
* Combinação e rejeição de classificadores

---

## I - Pré-processamento com Pandas e Scikit-learn


### 1 - Indrodução ao módulo

* Bases de dados:
    * dados de crédito
    * censo


* Carregamento de bases de dados


* Valores inconsistentes


* Valores faltantes


* Escalonamento de atributos


* Transformação de variáveis categóricas


* Introdução à avaliação de algoritmos


* Base de dados de treinamento e base de dados de teste


* Recursos do Pandas: localizar, remover linhas e colunas, alterar valores, etc)

---

### 2 - Tipos de variáveis

* numéricas

    * contínuas
        * números reais (float): 2.7, 44.3
        * exemplos: temperatura, peso, altura, salário      
        
    * discretas
        * conjunto de valores finitos (inteiros)
        * exemplo: contagem de alguma coisa
    
    
* categóricas

    * nominal
        * dados não mensuráveis
        * sem ordenação
        * exemplos: cor dos olhos, gênero, ID, nome
    
    * ordinal
        * categorizado sob uma ordenação
        * ordenado
        * exemplo: tamanho P, M e G

---

### 3 - Base de dados de crédito

* ./data/credit-data.csv

In [9]:
import pandas as pd
credit_data = pd.read_csv('./data/credit-data.csv')

In [10]:
type(credit_data)

pandas.core.frame.DataFrame

In [11]:
credit_data

clientid        income        age          loan  default
0            1  66155.925095  59.017015   8106.532131        0
1            2  34415.153966  48.117153   6564.745018        0
2            3  57317.170063  63.108049   8020.953296        0
3            4  42709.534201  45.751972   6103.642260        0
4            5  66952.688845  18.584336   8770.099235        1
5            6  24904.064140  57.471607     15.498598        0
6            7  48430.359613  26.809132   5722.581981        0
7            8  24500.141984  32.897548   2971.003310        1
8            9  40654.892537  55.496853   4755.825280        0
9           10  25075.872771  39.776378   1409.230371        0
10          11  64131.415372  25.679575   4351.028971        0
11          12  59436.847123  60.471936   9254.244538        0
12          13  61050.346079  26.355044   5893.264659        0
13          14  27267.995458  61.576776   4759.787581        0
14          15  63061.960174  39.201553   1850.369377        0
15          16  50501.726689 -28.218361   3977.287432        0
16          17  43548.654711  39.574530   3935.544453        0
17          18  43378.175194  60.848318   3277.737553        0
18          19  20542.365073  61.690571   3157.442290        0
19          20  58887.357549  26.076093   4965.516066        0
20          21  23000.784002  31.761354   1148.118057        0
21          22  32197.620701 -52.423280   4244.057136        0
22          23  23329.319414  48.576975    222.622299        0
23          24  27845.800894  51.970624   4959.921226        0
24          25  65301.984029  48.840922   5465.267886        0
25          26  47451.630123  27.031741   5361.282716        0
26          27  63287.038908 -36.496976   9595.286289        0
27          28  45727.459870  55.839922   6376.822949        0
28          29  59417.805406        NaN   2082.625938        0
29          30  58842.891308  54.510948  10871.186790        0
...        ...           ...        ...           ...      ...
1970      1971  68047.925311  47.694520   4023.064765        0
1971      1972  36275.735863  30.308184    644.384195        0
1972      1973  52389.366848  54.969313  10398.820592        0
1973      1974  23678.376111  47.466485   1779.814597        0
1974      1975  37707.642948  31.344048    268.290971        0
1975      1976  57753.568962  54.235915   5067.449964        0
1976      1977  30529.963288  47.604402   6046.840845        0
1977      1978  44022.268737  31.192627   1707.672870        0
1978      1979  58533.884683  40.518963   7832.443321        0
1979      1980  33702.531834  48.148404    922.036590        0
1980      1981  40236.872067  52.580773   4354.314412        0
1981      1982  62619.155988  43.999461   3959.611772        0
1982      1983  50738.362193  45.993199   9719.562798        0
1983      1984  64466.760138  33.327144   8537.369666        1
1984      1985  64636.402186  60.886966   2583.106425        0
1985      1986  22371.522191  39.142225   2291.856428        0
1986      1987  67994.988470  38.622259   7289.014109        0
1987      1988  49640.004702  20.542409   5760.858734        0
1988      1989  42067.246446  24.270612   4601.606183        0
1989      1990  43662.092688  25.252609   7269.596897        1
1990      1991  34237.575419  34.101654   2658.090632        0
1991      1992  26300.446554  45.539385   2317.393678        0
1992      1993  30803.806165  23.250084    623.024153        0
1993      1994  54421.410155  26.821928   3273.631823        0
1994      1995  24254.700791  37.751622   2225.284643        0
1995      1996  59221.044874  48.518179   1926.729397        0
1996      1997  69516.127573  23.162104   3503.176156        0
1997      1998  44311.449262  28.017167   5522.786693        1
1998      1999  43756.056605  63.971796   1622.722598        0
1999      2000  69436.579552  56.152617   7378.833599        0

[2000 rows x 5 columns]

In [12]:
credit_data.describe()

clientid        income          age          loan      default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

---

### 4 - Tratamento de valores inconsistentes

* registros com idade negativa
* necessário corrigir

In [13]:
# selecionar os registros que possuem a idade negativa
credit_data.loc[credit_data['age'] < 0]

clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

In [14]:
# Primeira técnica de tratamento dos valores inconsistentes: apagar a coluna dos dados inconsistentes
credit_data.drop('age', 1, inplace=True)

In [15]:
# Foi apagada a coluna age para todos os registros. Não é uma boa abordagem, porque perdemos a informação 
# por causa de apenas 3 registros inconsistentes
credit_data

clientid        income          loan  default
0            1  66155.925095   8106.532131        0
1            2  34415.153966   6564.745018        0
2            3  57317.170063   8020.953296        0
3            4  42709.534201   6103.642260        0
4            5  66952.688845   8770.099235        1
5            6  24904.064140     15.498598        0
6            7  48430.359613   5722.581981        0
7            8  24500.141984   2971.003310        1
8            9  40654.892537   4755.825280        0
9           10  25075.872771   1409.230371        0
10          11  64131.415372   4351.028971        0
11          12  59436.847123   9254.244538        0
12          13  61050.346079   5893.264659        0
13          14  27267.995458   4759.787581        0
14          15  63061.960174   1850.369377        0
15          16  50501.726689   3977.287432        0
16          17  43548.654711   3935.544453        0
17          18  43378.175194   3277.737553        0
18          19  20542.365073   3157.442290        0
19          20  58887.357549   4965.516066        0
20          21  23000.784002   1148.118057        0
21          22  32197.620701   4244.057136        0
22          23  23329.319414    222.622299        0
23          24  27845.800894   4959.921226        0
24          25  65301.984029   5465.267886        0
25          26  47451.630123   5361.282716        0
26          27  63287.038908   9595.286289        0
27          28  45727.459870   6376.822949        0
28          29  59417.805406   2082.625938        0
29          30  58842.891308  10871.186790        0
...        ...           ...           ...      ...
1970      1971  68047.925311   4023.064765        0
1971      1972  36275.735863    644.384195        0
1972      1973  52389.366848  10398.820592        0
1973      1974  23678.376111   1779.814597        0
1974      1975  37707.642948    268.290971        0
1975      1976  57753.568962   5067.449964        0
1976      1977  30529.963288   6046.840845        0
1977      1978  44022.268737   1707.672870        0
1978      1979  58533.884683   7832.443321        0
1979      1980  33702.531834    922.036590        0
1980      1981  40236.872067   4354.314412        0
1981      1982  62619.155988   3959.611772        0
1982      1983  50738.362193   9719.562798        0
1983      1984  64466.760138   8537.369666        1
1984      1985  64636.402186   2583.106425        0
1985      1986  22371.522191   2291.856428        0
1986      1987  67994.988470   7289.014109        0
1987      1988  49640.004702   5760.858734        0
1988      1989  42067.246446   4601.606183        0
1989      1990  43662.092688   7269.596897        1
1990      1991  34237.575419   2658.090632        0
1991      1992  26300.446554   2317.393678        0
1992      1993  30803.806165    623.024153        0
1993      1994  54421.410155   3273.631823        0
1994      1995  24254.700791   2225.284643        0
1995      1996  59221.044874   1926.729397        0
1996      1997  69516.127573   3503.176156        0
1997      1998  44311.449262   5522.786693        1
1998      1999  43756.056605   1622.722598        0
1999      2000  69436.579552   7378.833599        0

[2000 rows x 4 columns]

In [16]:
# Recarregar os dados para aplicar a segunda técnica de tratamento de dados inconsistentes:
credit_data = pd.read_csv('./data/credit-data.csv')

In [18]:
# Segunda técnica de tratamento dos valores inconsistentes: apagar somente os registros com problema
credit_data.drop(credit_data[credit_data.age < 0].index, inplace=True)

In [19]:
# Agora foram apagados apenas os 3 registros com problema. Também não é a melhor abordagem, pois os outros
# atributos dos registros removidos podem ser importantes.
credit_data

clientid        income        age          loan  default
0            1  66155.925095  59.017015   8106.532131        0
1            2  34415.153966  48.117153   6564.745018        0
2            3  57317.170063  63.108049   8020.953296        0
3            4  42709.534201  45.751972   6103.642260        0
4            5  66952.688845  18.584336   8770.099235        1
5            6  24904.064140  57.471607     15.498598        0
6            7  48430.359613  26.809132   5722.581981        0
7            8  24500.141984  32.897548   2971.003310        1
8            9  40654.892537  55.496853   4755.825280        0
9           10  25075.872771  39.776378   1409.230371        0
10          11  64131.415372  25.679575   4351.028971        0
11          12  59436.847123  60.471936   9254.244538        0
12          13  61050.346079  26.355044   5893.264659        0
13          14  27267.995458  61.576776   4759.787581        0
14          15  63061.960174  39.201553   1850.369377        0
16          17  43548.654711  39.574530   3935.544453        0
17          18  43378.175194  60.848318   3277.737553        0
18          19  20542.365073  61.690571   3157.442290        0
19          20  58887.357549  26.076093   4965.516066        0
20          21  23000.784002  31.761354   1148.118057        0
22          23  23329.319414  48.576975    222.622299        0
23          24  27845.800894  51.970624   4959.921226        0
24          25  65301.984029  48.840922   5465.267886        0
25          26  47451.630123  27.031741   5361.282716        0
27          28  45727.459870  55.839922   6376.822949        0
28          29  59417.805406        NaN   2082.625938        0
29          30  58842.891308  54.510948  10871.186790        0
30          31  48528.852796        NaN   6155.784670        0
31          32  23526.302555        NaN   2862.010139        0
32          33  67252.900607  38.131907   4221.303157        0
...        ...           ...        ...           ...      ...
1970      1971  68047.925311  47.694520   4023.064765        0
1971      1972  36275.735863  30.308184    644.384195        0
1972      1973  52389.366848  54.969313  10398.820592        0
1973      1974  23678.376111  47.466485   1779.814597        0
1974      1975  37707.642948  31.344048    268.290971        0
1975      1976  57753.568962  54.235915   5067.449964        0
1976      1977  30529.963288  47.604402   6046.840845        0
1977      1978  44022.268737  31.192627   1707.672870        0
1978      1979  58533.884683  40.518963   7832.443321        0
1979      1980  33702.531834  48.148404    922.036590        0
1980      1981  40236.872067  52.580773   4354.314412        0
1981      1982  62619.155988  43.999461   3959.611772        0
1982      1983  50738.362193  45.993199   9719.562798        0
1983      1984  64466.760138  33.327144   8537.369666        1
1984      1985  64636.402186  60.886966   2583.106425        0
1985      1986  22371.522191  39.142225   2291.856428        0
1986      1987  67994.988470  38.622259   7289.014109        0
1987      1988  49640.004702  20.542409   5760.858734        0
1988      1989  42067.246446  24.270612   4601.606183        0
1989      1990  43662.092688  25.252609   7269.596897        1
1990      1991  34237.575419  34.101654   2658.090632        0
1991      1992  26300.446554  45.539385   2317.393678        0
1992      1993  30803.806165  23.250084    623.024153        0
1993      1994  54421.410155  26.821928   3273.631823        0
1994      1995  24254.700791  37.751622   2225.284643        0
1995      1996  59221.044874  48.518179   1926.729397        0
1996      1997  69516.127573  23.162104   3503.176156        0
1997      1998  44311.449262  28.017167   5522.786693        1
1998      1999  43756.056605  63.971796   1622.722598        0
1999      2000  69436.579552  56.152617   7378.833599        0

[1997 rows x 5 columns]

In [20]:
# Terceira técnica de tratamento dos valores inconsistentes: preencher manualmente os valores inconsistentes
# Geralmente é inviável, pois podem ser muitos registros com problema, e não temos acesso ao valor correto 
# para preencher.

In [22]:
# Recarregar os dados para aplicar a quarta técnica de tratamento de dados inconsistentes:
credit_data = pd.read_csv('./data/credit-data.csv')

In [23]:
# Quarta técnica de tratamento dos valores inconsistentes: preencher os valores inconsistentes com a média 
# do atributo
credit_data.mean()

clientid     1000.500000
income      45331.600018
age            40.807559
loan         4444.369695
default         0.141500
dtype: float64

In [24]:
credit_data['age'].mean()

40.80755937840458

In [26]:
# esta média não está correta, pois foram utilizadas as 3 idades negativas
# corrigindo o cálculo:
age_mean = credit_data['age'][credit_data.age > 0].mean()
age_mean

40.92770044906149

In [27]:
# atualizando os registros com a idade inconsistente:
credit_data.loc[credit_data.age < 0, 'age'] = age_mean

In [28]:
credit_data

clientid        income        age          loan  default
0            1  66155.925095  59.017015   8106.532131        0
1            2  34415.153966  48.117153   6564.745018        0
2            3  57317.170063  63.108049   8020.953296        0
3            4  42709.534201  45.751972   6103.642260        0
4            5  66952.688845  18.584336   8770.099235        1
5            6  24904.064140  57.471607     15.498598        0
6            7  48430.359613  26.809132   5722.581981        0
7            8  24500.141984  32.897548   2971.003310        1
8            9  40654.892537  55.496853   4755.825280        0
9           10  25075.872771  39.776378   1409.230371        0
10          11  64131.415372  25.679575   4351.028971        0
11          12  59436.847123  60.471936   9254.244538        0
12          13  61050.346079  26.355044   5893.264659        0
13          14  27267.995458  61.576776   4759.787581        0
14          15  63061.960174  39.201553   1850.369377        0
15          16  50501.726689  40.927700   3977.287432        0
16          17  43548.654711  39.574530   3935.544453        0
17          18  43378.175194  60.848318   3277.737553        0
18          19  20542.365073  61.690571   3157.442290        0
19          20  58887.357549  26.076093   4965.516066        0
20          21  23000.784002  31.761354   1148.118057        0
21          22  32197.620701  40.927700   4244.057136        0
22          23  23329.319414  48.576975    222.622299        0
23          24  27845.800894  51.970624   4959.921226        0
24          25  65301.984029  48.840922   5465.267886        0
25          26  47451.630123  27.031741   5361.282716        0
26          27  63287.038908  40.927700   9595.286289        0
27          28  45727.459870  55.839922   6376.822949        0
28          29  59417.805406        NaN   2082.625938        0
29          30  58842.891308  54.510948  10871.186790        0
...        ...           ...        ...           ...      ...
1970      1971  68047.925311  47.694520   4023.064765        0
1971      1972  36275.735863  30.308184    644.384195        0
1972      1973  52389.366848  54.969313  10398.820592        0
1973      1974  23678.376111  47.466485   1779.814597        0
1974      1975  37707.642948  31.344048    268.290971        0
1975      1976  57753.568962  54.235915   5067.449964        0
1976      1977  30529.963288  47.604402   6046.840845        0
1977      1978  44022.268737  31.192627   1707.672870        0
1978      1979  58533.884683  40.518963   7832.443321        0
1979      1980  33702.531834  48.148404    922.036590        0
1980      1981  40236.872067  52.580773   4354.314412        0
1981      1982  62619.155988  43.999461   3959.611772        0
1982      1983  50738.362193  45.993199   9719.562798        0
1983      1984  64466.760138  33.327144   8537.369666        1
1984      1985  64636.402186  60.886966   2583.106425        0
1985      1986  22371.522191  39.142225   2291.856428        0
1986      1987  67994.988470  38.622259   7289.014109        0
1987      1988  49640.004702  20.542409   5760.858734        0
1988      1989  42067.246446  24.270612   4601.606183        0
1989      1990  43662.092688  25.252609   7269.596897        1
1990      1991  34237.575419  34.101654   2658.090632        0
1991      1992  26300.446554  45.539385   2317.393678        0
1992      1993  30803.806165  23.250084    623.024153        0
1993      1994  54421.410155  26.821928   3273.631823        0
1994      1995  24254.700791  37.751622   2225.284643        0
1995      1996  59221.044874  48.518179   1926.729397        0
1996      1997  69516.127573  23.162104   3503.176156        0
1997      1998  44311.449262  28.017167   5522.786693        1
1998      1999  43756.056605  63.971796   1622.722598        0
1999      2000  69436.579552  56.152617   7378.833599        0

[2000 rows x 5 columns]

---

### 5 - Tratamento de valores faltantes

In [45]:
# verificando se existem registros com idade nula
pd.isnull(credit_data['age'])

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28       True
29      False
        ...  
1970    False
1971    False
1972    False
1973    False
1974    False
1975    False
1976    False
1977    False
1978    False
1979    False
1980    False
1981    False
1982    False
1983    False
1984    False
1985    False
1986    False
1987    False
1988    False
1989    False
1990    False
1991    False
1992    False
1993    False
1994    False
1995    False
1996    False
1997    False
1998    False
1999    False
Name: age, Length: 2000, dtype: bool

In [46]:
# selecionando os registros com idade nula
credit_data.loc[pd.isnull(credit_data['age'])]

clientid        income  age         loan  default
28        29  59417.805406  NaN  2082.625938        0
30        31  48528.852796  NaN  6155.784670        0
31        32  23526.302555  NaN  2862.010139        0

In [48]:
# dividindo a base de dados em atributos previsores e atributo classe
# o atributo clientid não será utilizado no algoritmo de aprendizado
predict_attrs = credit_data.iloc[:, 1:4].values
predict_attrs[25:35,]

array([[4.74516301e+04, 2.70317413e+01, 5.36128272e+03],
       [6.32870389e+04, 4.09277004e+01, 9.59528629e+03],
       [4.57274599e+04, 5.58399218e+01, 6.37682295e+03],
       [5.94178054e+04,            nan, 2.08262594e+03],
       [5.88428913e+04, 5.45109476e+01, 1.08711868e+04],
       [4.85288528e+04,            nan, 6.15578467e+03],
       [2.35263026e+04,            nan, 2.86201014e+03],
       [6.72529006e+04, 3.81319075e+01, 4.22130316e+03],
       [5.88868513e+04, 3.86615042e+01, 7.27155203e+03],
       [5.75849738e+04, 3.66720209e+01, 1.72842375e+03]])

In [49]:
class_attr = credit_data.iloc[:, 4].values
class_attr

array([0, 0, 0, ..., 1, 0, 0])

In [35]:
from sklearn.preprocessing import Imputer

help(Imputer)

Help on class Imputer in module sklearn.preprocessing.imputation:

class Imputer(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  Imputation transformer for completing missing values.
 |  
 |  Read more in the :ref:`User Guide <imputation>`.
 |  
 |  Parameters
 |  ----------
 |  missing_values : integer or "NaN", optional (default="NaN")
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For missing values encoded as np.nan,
 |      use the string value "NaN".
 |  
 |  strategy : string, optional (default="mean")
 |      The imputation strategy.
 |  
 |      - If "mean", then replace missing values using the mean along
 |        the axis.
 |      - If "median", then replace missing values using the median along
 |        the axis.
 |      - If "most_frequent", then replace missing using the most frequent
 |        value along the axis.
 |  
 |  axis : integer, optional (default=0)
 |      The axis along which to i

In [56]:
# a classe sklearn.preprocessing.imputation.Imputer foi descontinuada
# então, vamos usar a nova classe SimpleImputer
from sklearn.impute import SimpleImputer
import numpy as np

In [60]:
# aplicar a transformação dos valores faltantes pela média do respectivo atributo
imputer = SimpleImputer(missing_values=np.nan, strategy='mean', copy=False)
imputer.fit(predict_attrs)
imputer.transform(predict_attrs)
predict_attrs[25:35,]

array([[4.74516301e+04, 2.70317413e+01, 5.36128272e+03],
       [6.32870389e+04, 4.09277004e+01, 9.59528629e+03],
       [4.57274599e+04, 5.58399218e+01, 6.37682295e+03],
       [5.94178054e+04, 4.09277004e+01, 2.08262594e+03],
       [5.88428913e+04, 5.45109476e+01, 1.08711868e+04],
       [4.85288528e+04, 4.09277004e+01, 6.15578467e+03],
       [2.35263026e+04, 4.09277004e+01, 2.86201014e+03],
       [6.72529006e+04, 3.81319075e+01, 4.22130316e+03],
       [5.88868513e+04, 3.86615042e+01, 7.27155203e+03],
       [5.75849738e+04, 3.66720209e+01, 1.72842375e+03]])

---

### 6 - Escalonamento de atributos

Colocar os valores dos atributos na mesma escala. Como mostrado no array anterior, os 3 atributos estão em escalas diferentes. É necessário fazer o escalonamento para que os algoritmos funcionem corretamente, principalmente se forem baseados em distância euclidiana (KNN por exemplo, vai considerar os valores maiores como mais importantes).

Mesmo se o algoritmo utilizado não for baseado em distância euclidiana, o escalonamento faz com que o algoritmo execute de forma mais rápida.

Duas formas de escalonamento:

* Padronização (standardisation): $x = \dfrac{x - mean(x)}{std(x)}$


* Normalização (normalization): $x = \dfrac{x - min(x)}{max(x) - min(x)}$

In [61]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
predict_attrs = scaler.fit_transform(predict_attrs)
predict_attrs

array([[ 1.45393393,  1.36538005,  1.20281942],
       [-0.76217555,  0.54265932,  0.69642695],
       [ 0.83682073,  1.67417101,  1.17471147],
       ...,
       [-0.07122592, -0.97448606,  0.35420081],
       [-0.11000289,  1.73936652, -0.92675625],
       [ 1.682986  ,  1.14917551,  0.96381038]])

---

### 7  - Base de dados do censo

UCI - Machine Learning Repository: http://archive.ics.uci.edu/ml/datasets.html

In [62]:
import pandas as pd

census_data = pd.read_csv('./data/census.csv')
census_data

age          workclass  final-weight      education  education-num  \
0       39          State-gov         77516      Bachelors             13   
1       50   Self-emp-not-inc         83311      Bachelors             13   
2       38            Private        215646        HS-grad              9   
3       53            Private        234721           11th              7   
4       28            Private        338409      Bachelors             13   
5       37            Private        284582        Masters             14   
6       49            Private        160187            9th              5   
7       52   Self-emp-not-inc        209642        HS-grad              9   
8       31            Private         45781        Masters             14   
9       42            Private        159449      Bachelors             13   
10      37            Private        280464   Some-college             10   
11      30          State-gov        141297      Bachelors             13   
12      23            Private        122272      Bachelors             13   
13      32            Private        205019     Assoc-acdm             12   
14      40            Private        121772      Assoc-voc             11   
15      34            Private        245487        7th-8th              4   
16      25   Self-emp-not-inc        176756        HS-grad              9   
17      32            Private        186824        HS-grad              9   
18      38            Private         28887           11th              7   
19      43   Self-emp-not-inc        292175        Masters             14   
20      40            Private        193524      Doctorate             16   
21      54            Private        302146        HS-grad              9   
22      35        Federal-gov         76845            9th              5   
23      43            Private        117037           11th              7   
24      59            Private        109015        HS-grad              9   
25      56          Local-gov        216851      Bachelors             13   
26      19            Private        168294        HS-grad              9   
27      54                  ?        180211   Some-college             10   
28      39            Private        367260        HS-grad              9   
29      49            Private        193366        HS-grad              9   
...    ...                ...           ...            ...            ...   
32531   30                  ?         33811      Bachelors             13   
32532   34            Private        204461      Doctorate             16   
32533   54            Private        337992      Bachelors             13   
32534   37            Private        179137   Some-college             10   
32535   22            Private        325033           12th              8   
32536   34            Private        160216      Bachelors             13   
32537   30            Private        345898        HS-grad              9   
32538   38            Private        139180      Bachelors             13   
32539   71                  ?        287372      Doctorate             16   
32540   45          State-gov        252208        HS-grad              9   
32541   41                  ?        202822        HS-grad              9   
32542   72                  ?        129912        HS-grad              9   
32543   45          Local-gov        119199     Assoc-acdm             12   
32544   31            Private        199655        Masters             14   
32545   39          Local-gov        111499     Assoc-acdm             12   
32546   37            Private        198216     Assoc-acdm             12   
32547   43            Private        260761        HS-grad              9   
32548   65   Self-emp-not-inc         99359    Prof-school             15   
32549   43          State-gov        255835   Some-college             10   
32550   43   Self-emp-not-inc         27242   Some-college             10   
325

**Tipos das variáveis dos atributos:**

* age: numérica, discreta
* workclass: categórica, nominal
* final-weight: numérica, contínua
* education: categórica, ordinal
* education-num: numérica, discreta
* marital-status: categórica, nominal
* occupation: categórica, nominal
* relationship: categórica, nominal
* race: categórica, nominal
* sex: categórica, nominal
* capital-gain: numérica, discreta
* capital-loos: numérica, discreta
* hour-per-week: numérica, discreta
* native-country: categórica, nominal


* income: é o atributo de classe

---

### 8 - Transformação de variáveis categóricas (I)

É necessário transformar os atributos com variáveis categóricas em variáveis numéricas, porque os algoritmos de aprendizagem de máquina trabalham com cálculos numéricos e equações.

In [63]:
census_predict_attrs = census_data.iloc[:, 0:14].values
census_predict_attrs

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [64]:
census_class_attr = census_data.iloc[:, 14].values
census_class_attr

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [65]:
from sklearn.preprocessing import LabelEncoder
labelencoder_census_predict_attrs = LabelEncoder()

In [68]:
# exemplo de transformação do atributo workclass em variável numérica
workclass_labels = labelencoder_census_predict_attrs.fit_transform(census_predict_attrs[:,1])
workclass_labels

array([7, 6, 4, ..., 4, 4, 5])

In [70]:
census_predict_attrs[:, 1] = labelencoder_census_predict_attrs.fit_transform(census_predict_attrs[:,1])
census_predict_attrs[:, 3] = labelencoder_census_predict_attrs.fit_transform(census_predict_attrs[:,3])
census_predict_attrs[:, 5] = labelencoder_census_predict_attrs.fit_transform(census_predict_attrs[:,5])
census_predict_attrs[:, 6] = labelencoder_census_predict_attrs.fit_transform(census_predict_attrs[:,6])
census_predict_attrs[:, 7] = labelencoder_census_predict_attrs.fit_transform(census_predict_attrs[:,7])
census_predict_attrs[:, 8] = labelencoder_census_predict_attrs.fit_transform(census_predict_attrs[:,8])
census_predict_attrs[:, 9] = labelencoder_census_predict_attrs.fit_transform(census_predict_attrs[:,9])
census_predict_attrs[:, 13] = labelencoder_census_predict_attrs.fit_transform(census_predict_attrs[:,13])

census_predict_attrs

array([[39, 7, 77516, ..., 0, 40, 39],
       [50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)